.TH IMAGINATION 1 "2009-05-12" "1.0" "DVD slide show maker"

.SH NAME
imagination \- DVD slide show maker

.SH SYNOPSIS
\fBimagination\fR

.SH DESCRIPTION
Imagination is a lightweight and user-friendly DVD slide show maker. It includes transitions effects. It requires only the ffmpeg encoder to produce a movie to be burned with another application.

.SH OPTIONS
imagination has no options.

.SH HOMEPAGE
More information about imagination can be found at <\fIhttp://imagination.sourceforge.net/\fR>.

.SH AUTHOR
imagination was written by Giuseppe Torelli <\fIcolossus73@gmail.com\fR> and Tadej Borovsak <\fItadeboro@gmail.com\fR>.
.PP
This manual page was written by Daniel Baumann <\fIdaniel@debian.org\fR>, for the Debian project (but may be used by others).
